using System.Collections.Frozen;

namespace RuneshapePriceChecker.Pricing;

internal static class UniqueItemTypeLookup
{
    private static readonly FrozenDictionary<string, string> Map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        // === One Hand Maces ===
        ["BRYNHAND'S MARK"] = "ONE HAND MACE",
        ["FROSTBREATH"] = "ONE HAND MACE",
        ["TRENCHTIMBRE"] = "ONE HAND MACE",
        ["SCULPTED SUFFERING"] = "ONE HAND MACE",
        ["BRUTUS' LEAD SPRINKLER"] = "ONE HAND MACE",
        ["SERLE'S GRIT"] = "ONE HAND MACE",
        ["SEEING STARS"] = "ONE HAND MACE",
        ["NEBULOCH"] = "ONE HAND MACE",
        ["MJÖLNER"] = "ONE HAND MACE",
        ["MJOLNER"] = "ONE HAND MACE",
        ["OLROVASARA"] = "ONE HAND MACE",
        ["SADIST'S MERCY"] = "ONE HAND MACE",

        // === Two Hand Maces ===
        ["HOGHUNT"] = "TWO HAND MACE",
        ["HRIMNOR'S HYMN"] = "TWO HAND MACE",
        ["TREPHINA"] = "TWO HAND MACE",
        ["BRAIN RATTLER"] = "TWO HAND MACE",
        ["THE EMPTY ROAR"] = "TWO HAND MACE",
        ["SHYABA"] = "TWO HAND MACE",
        ["CHOBER CHABER"] = "TWO HAND MACE",
        ["QUECHOLLI"] = "TWO HAND MACE",
        ["TIDEBREAKER"] = "TWO HAND MACE",
        ["MAROHI ERQI"] = "TWO HAND MACE",
        ["THE HAMMER OF FAITH"] = "TWO HAND MACE",
        ["TWISTED EMPYREAN"] = "TWO HAND MACE",

        // === Bows ===
        ["WIDOWHAIL"] = "BOW",
        ["QUILL RAIN"] = "BOW",
        ["IRONBOUND"] = "BOW",
        ["SPLINTERHEART"] = "BOW",
        ["DOOMFLETCH"] = "BOW",
        ["DEATH'S HARP"] = "BOW",
        ["SLIVERTONGUE"] = "BOW",
        ["FAIRGRAVES' CURSE"] = "BOW",
        ["LIONEYE'S GLARE"] = "BOW",
        ["PERIPHERY"] = "BOW",
        ["VOLTAXIC RIFT"] = "BOW",

        // === Crossbows ===
        ["MIST WHISPER"] = "CROSSBOW",
        ["RAMPART RAPTOR"] = "CROSSBOW",
        ["DOUBLE VISION"] = "CROSSBOW",
        ["REDEMPTION"] = "CROSSBOW",
        ["THE LAST LAMENT"] = "CROSSBOW",

        // === Quarterstaves ===
        ["THE BLOOD THORN"] = "QUARTERSTAFF",
        ["PILLAR OF THE CAGED GOD"] = "QUARTERSTAFF",
        ["THE SENTRY"] = "QUARTERSTAFF",
        ["MATSYA"] = "QUARTERSTAFF",
        ["NAZIR'S JUDGEMENT"] = "QUARTERSTAFF",
        ["COLLAPSING HORIZON"] = "QUARTERSTAFF",
        ["DUALITY"] = "QUARTERSTAFF",

        // === Spears ===
        ["SPLINTER OF LORRATA"] = "SPEAR",
        ["TYRANNY'S GRIP"] = "SPEAR",
        ["CHAINSTING"] = "SPEAR",
        ["SKYSLIVER"] = "SPEAR",
        ["TANGLETONGUE"] = "SPEAR",
        ["SAITHA'S SPEAR"] = "SPEAR",
        ["DAEVATA'S WIND"] = "SPEAR",
        ["SPIRE OF IRE"] = "SPEAR",
        ["ATZIRI'S CONTEMPT"] = "SPEAR",
        ["THE ORDAINED"] = "SPEAR",

        // === Staves ===
        ["DUSK VIGIL"] = "STAFF",
        ["EARTHBOUND"] = "STAFF",
        ["TARYN'S SHIVER"] = "STAFF",
        ["THE SEARING TOUCH"] = "STAFF",
        ["SIRE OF SHARDS"] = "STAFF",
        ["THE RAVEN'S FLOCK"] = "STAFF",
        ["ATZIRI'S RULE"] = "STAFF",
        ["THE BURDEN OF SHADOWS"] = "STAFF",
        ["THE WHISPERING ICE"] = "STAFF",
        ["THE UNBORN LICH"] = "STAFF",

        // === Wands ===
        ["THE WICKED QUILL"] = "WAND",
        ["LIFESPRIG"] = "WAND",
        ["SANGUINE DIVINER"] = "WAND",
        ["ENEZUN'S CHARGE"] = "WAND",
        ["CURSECARVER"] = "WAND",
        ["ADONIA'S EGO"] = "WAND",
        ["LIMINAL COIL"] = "WAND",
        ["RUNESEEKER'S CALL"] = "WAND",

        // === Sceptres ===
        ["THE DARK DEFILER"] = "SCEPTRE",
        ["FONT OF POWER"] = "SCEPTRE",
        ["SYLVAN'S EFFIGY"] = "SCEPTRE",
        ["GUIDING PALM OF THE EYE"] = "SCEPTRE",
        ["GUIDING PALM OF THE HEART"] = "SCEPTRE",
        ["GUIDING PALM OF THE MIND"] = "SCEPTRE",
        ["PALM OF THE DREAMER"] = "SCEPTRE",
        ["SACRED FLAME"] = "SCEPTRE",

        // === Foci ===
        ["DEATHRATTLE"] = "FOCUS",
        ["THREADED LIGHT"] = "FOCUS",
        ["EFFIGY OF CRUELTY"] = "FOCUS",
        ["CARRION CALL"] = "FOCUS",
        ["SERPENT'S LESSON"] = "FOCUS",
        ["THE ETERNAL SPARK"] = "FOCUS",
        ["APEP'S SUPREMACY"] = "FOCUS",
        ["RATHPITH GLOBE"] = "FOCUS",

        // === Shields ===
        ["DIONADAIR"] = "SHIELD",
        ["WULFSBANE"] = "SHIELD",
        ["DOOMGATE"] = "SHIELD",
        ["WINDOW TO PARADISE"] = "SHIELD",
        ["LYCOSIDAE"] = "SHIELD",
        ["REDBLADE BANNER"] = "SHIELD",
        ["SVALINN"] = "SHIELD",
        ["CHERNOBOG'S PILLAR"] = "SHIELD",
        ["NIGHTFALL"] = "SHIELD",
        ["THE SURRENDER"] = "SHIELD",
        ["ARVIL'S WHEEL"] = "SHIELD",
        ["FEATHERED FORTRESS"] = "SHIELD",
        ["EYES OF THE RUNEFATHER"] = "SHIELD",
        ["ALKEM EIRA"] = "SHIELD",
        ["OAKSWORN"] = "SHIELD",
        ["SAFFELL'S FRAME"] = "SHIELD",
        ["CREST OF ARDURA"] = "SHIELD",
        ["RISE OF THE PHOENIX"] = "SHIELD",
        ["MAHUXOTL'S MACHINATION"] = "SHIELD",
        ["PRISM GUARDIAN"] = "SHIELD",

        // === Quivers ===
        ["ASPHYXIA'S WRATH"] = "QUIVER",
        ["BLACKGLEAM"] = "QUIVER",
        ["THE LETHAL DRAW"] = "QUIVER",
        ["REARGUARD"] = "QUIVER",
        ["MURKSHAFT"] = "QUIVER",
        ["DRILLNECK"] = "QUIVER",
        ["BEYOND REACH"] = "QUIVER",
        ["CADIRO'S GAMBIT"] = "QUIVER",

        // === Talismans ===
        ["AMOR MANDRAGORA"] = "TALISMAN",
        ["SPITEFUL FLORET"] = "TALISMAN",
        ["HYSSEG'S CLAW"] = "TALISMAN",
        ["THE FLESH POPPET"] = "TALISMAN",
        ["SURGE OF THE TIDE"] = "TALISMAN",
        ["FURY OF THE KING"] = "TALISMAN",

        // === Body Armours ===
        ["BRAMBLEJACK"] = "BODY ARMOUR",
        ["BLACKBRAID"] = "BODY ARMOUR",
        ["EDYRN'S TUSKS"] = "BODY ARMOUR",
        ["TITANROT CATAPHRACT"] = "BODY ARMOUR",
        ["WANDERING RELIQUARY"] = "BODY ARMOUR",
        ["KINGSGUARD"] = "BODY ARMOUR",
        ["GREED'S EMBRACE"] = "BODY ARMOUR",
        ["THE BRASS DOME"] = "BODY ARMOUR",
        ["KAOM'S HEART"] = "BODY ARMOUR",
        ["BRISTLEBOAR"] = "BODY ARMOUR",
        ["FOXSHADE"] = "BODY ARMOUR",
        ["ASHREND"] = "BODY ARMOUR",
        ["SANDS OF SILK"] = "BODY ARMOUR",
        ["BRISKWRAP"] = "BODY ARMOUR",
        ["DUSTBLOOM"] = "BODY ARMOUR",
        ["THE RAT CAGE"] = "BODY ARMOUR",
        ["QUATL'S MOLT"] = "BODY ARMOUR",
        ["QUEEN OF THE FOREST"] = "BODY ARMOUR",
        ["YRIEL'S FOSTERING"] = "BODY ARMOUR",
        ["THE AUSPEX"] = "BODY ARMOUR",
        ["HYRRI'S IRE"] = "BODY ARMOUR",
        ["GHOSTWRITHE"] = "BODY ARMOUR",
        ["BITTERBLOOM"] = "BODY ARMOUR",
        ["THE BLACK DOUBT"] = "BODY ARMOUR",
        ["NECROMANTLE"] = "BODY ARMOUR",
        ["CLOAK OF FLAME"] = "BODY ARMOUR",
        ["PRAYERS FOR RAIN"] = "BODY ARMOUR",
        ["TETZLAPOKAL'S DESIRE"] = "BODY ARMOUR",
        ["THE COVENANT"] = "BODY ARMOUR",
        ["GLOAMGOWN"] = "BODY ARMOUR",
        ["VIS MORTIS"] = "BODY ARMOUR",
        ["TEMPORALIS"] = "BODY ARMOUR",
        ["CLOAK OF DEFIANCE"] = "BODY ARMOUR",
        ["SILKS OF VENERATION"] = "BODY ARMOUR",
        ["COAT OF RED"] = "BODY ARMOUR",
        ["THE BARROW DWELLER"] = "BODY ARMOUR",
        ["IRONGRASP"] = "BODY ARMOUR",
        ["PARIAH'S EMBRACE"] = "BODY ARMOUR",
        ["BELLY OF THE BEAST"] = "BODY ARMOUR",
        ["DORYANI'S PROTOTYPE"] = "BODY ARMOUR",
        ["PERFIDY"] = "BODY ARMOUR",
        ["THE SUNKEN VESSEL"] = "BODY ARMOUR",
        ["WIDOW'S REIGN"] = "BODY ARMOUR",
        ["PRAGMATISM"] = "BODY ARMOUR",
        ["LIGHTNING COIL"] = "BODY ARMOUR",
        ["THE COMING CALAMITY"] = "BODY ARMOUR",
        ["ENFOLDING DAWN"] = "BODY ARMOUR",
        ["ICETOMB"] = "BODY ARMOUR",
        ["REVERIE"] = "BODY ARMOUR",
        ["SOUL MANTLE"] = "BODY ARMOUR",
        ["LOREWEAVE"] = "BODY ARMOUR",
        ["THE MUTABLE STAR"] = "BODY ARMOUR",
        ["WAVESHAPER"] = "BODY ARMOUR",
        ["COUTURE OF CRIMSON"] = "BODY ARMOUR",
        ["VOLL'S PROTECTOR"] = "BODY ARMOUR",
        ["GEOFRI'S SANCTUARY"] = "BODY ARMOUR",
        ["THE UNLEASHED"] = "BODY ARMOUR",
        ["SACROSANCTUM"] = "BODY ARMOUR",
        ["DECREE OF LOYALTY"] = "BODY ARMOUR",
        ["APRON OF EMIRAN"] = "BODY ARMOUR",
        ["GLOOMFORM"] = "BODY ARMOUR",
        ["SIERRAN INHERITANCE"] = "BODY ARMOUR",
        ["THE DANCING MIRAGE"] = "BODY ARMOUR",
        ["REDFLARE CONDUIT"] = "BODY ARMOUR",
        ["ZERPHI'S SERAPE"] = "BODY ARMOUR",
        ["FORGOTTEN WARDEN"] = "BODY ARMOUR",
        ["COSMRI'S WILL"] = "BODY ARMOUR",
        ["ATZIRI'S SPLENDOUR"] = "BODY ARMOUR",
        ["MORIOR INVICTUS"] = "BODY ARMOUR",
        ["SKIN OF THE LOYAL"] = "BODY ARMOUR",
        ["TABULA RASA"] = "BODY ARMOUR",

        // === Helmets ===
        ["HORNS OF BYNDEN"] = "HELMET",
        ["WINGS OF CAELYN"] = "HELMET",
        ["EZOMYTE PEAK"] = "HELMET",
        ["BLACK SUN CREST"] = "HELMET",
        ["THRILLSTEEL"] = "HELMET",
        ["DEIDBELL"] = "HELMET",
        ["BLOOD PRICE"] = "HELMET",
        ["CORONA OF THE RED SUN"] = "HELMET",
        ["INNSMOUTH"] = "HELMET",
        ["GOLDRIM"] = "HELMET",
        ["RADIANT GRIEF"] = "HELMET",
        ["ELEVORE"] = "HELMET",
        ["CONSTRICTING COMMAND"] = "HELMET",
        ["THE BLACK INSIGNIA"] = "HELMET",
        ["STARKONJA'S HEAD"] = "HELMET",
        ["HEATSHIVER"] = "HELMET",
        ["MYRIS UXOR"] = "HELMET",
        ["ALPHA'S HOWL"] = "HELMET",
        ["CROWN OF THORNS"] = "HELMET",
        ["THE DEVOURING DIADEM"] = "HELMET",
        ["VISAGE OF AYAH"] = "HELMET",
        ["MASK OF THE STITCHED DEMON"] = "HELMET",
        ["ATZIRI'S DISDAIN"] = "HELMET",
        ["CROWN OF EYES"] = "HELMET",
        ["SCOLD'S BRIDLE"] = "HELMET",
        ["SANDSTORM VISAGE"] = "HELMET",
        ["INDIGON"] = "HELMET",
        ["GREYMAKE"] = "HELMET",
        ["IRONRIDE"] = "HELMET",
        ["THE SMILING KNIGHT"] = "HELMET",
        ["THE VILE KNIGHT"] = "HELMET",
        ["ASSAILUM"] = "HELMET",
        ["THE BRINGER OF RAIN"] = "HELMET",
        ["DECREE OF ACUITY"] = "HELMET",
        ["CROWN OF THE VICTOR"] = "HELMET",
        ["BRONZEBEARD"] = "HELMET",
        ["CROWN OF THE PALE KING"] = "HELMET",
        ["VEIL OF THE NIGHT"] = "HELMET",
        ["CORNATHAUM"] = "HELMET",
        ["KEEPER OF THE ARC"] = "HELMET",
        ["VESTIGE OF DARKNESS"] = "HELMET",
        ["THE HOLLOW MASK"] = "HELMET",
        ["MASK OF THE SANGUIMANCER"] = "HELMET",
        ["LEER CAST"] = "HELMET",
        ["ATSAK'S SIGHT"] = "HELMET",
        ["THE VERTEX"] = "HELMET",
        ["THE THREE DRAGONS"] = "HELMET",
        ["GLIMPSE OF CHAOS"] = "HELMET",
        ["MIND OF THE COUNCIL"] = "HELMET",
        ["ERIAN'S COBBLE"] = "HELMET",
        ["SOLUS IPSE"] = "HELMET",

        // === Gloves ===
        ["FACEBREAKER"] = "GLOVES",
        ["TREEFINGERS"] = "GLOVES",
        ["LOCHTONIAL CARESS"] = "GLOVES",
        ["DREADFIST"] = "GLOVES",
        ["ATZIRI'S ACUITY"] = "GLOVES",
        ["EMPIRE'S GRASP"] = "GLOVES",
        ["HATEFORGE"] = "GLOVES",
        ["NORTHPAW"] = "GLOVES",
        ["GRIP OF WINTER"] = "GLOVES",
        ["IDLE HANDS"] = "GLOVES",
        ["SNAKEBITE"] = "GLOVES",
        ["MALIGARO'S VIRTUOSITY"] = "GLOVES",
        ["HORROR'S FLIGHT"] = "GLOVES",
        ["PAINTER'S SERVANT"] = "GLOVES",
        ["CANDLEMAKER"] = "GLOVES",
        ["DOEDRE'S TENURE"] = "GLOVES",
        ["KITOKO'S CURRENT"] = "GLOVES",
        ["DEMON STITCHER"] = "GLOVES",
        ["NIGHTSCALE"] = "GLOVES",
        ["LEOPOLD'S APPLAUSE"] = "GLOVES",
        ["JARNGREIPR"] = "GLOVES",
        ["AURSEIZE"] = "GLOVES",
        ["DEATHBLOW"] = "GLOVES",
        ["VALAKO'S VICE"] = "GLOVES",
        ["AERISVANE'S WINGS"] = "GLOVES",
        ["DEATH ARTICULATED"] = "GLOVES",
        ["GRAVEBIND"] = "GLOVES",
        ["SHACKLES OF THE WRETCHED"] = "GLOVES",
        ["BLUEFLAME BRACERS"] = "GLOVES",
        ["THE PRISONER'S MANACLES"] = "GLOVES",
        ["PLAGUEFINGER"] = "GLOVES",
        ["KILLJOY"] = "GLOVES",
        ["HAND OF WISDOM AND ACTION"] = "GLOVES",
        ["ESSENTIA SANGUIS"] = "GLOVES",
        ["THUNDERFIST"] = "GLOVES",
        ["SINE AEQUO"] = "GLOVES",

        // === Boots ===
        ["LEGIONSTRIDE"] = "BOOTS",
        ["CORPSEWADE"] = "BOOTS",
        ["THE INFINITE PURSUIT"] = "BOOTS",
        ["TRAMPLETOE"] = "BOOTS",
        ["BIRTH OF FURY"] = "BOOTS",
        ["BRIARPATCH"] = "BOOTS",
        ["GAMBLESPRINT"] = "BOOTS",
        ["BUSHWHACK"] = "BOOTS",
        ["ATZIRI'S STEP"] = "BOOTS",
        ["LUMINOUS PACE"] = "BOOTS",
        ["WANDERLUST"] = "BOOTS",
        ["BONES OF ULLR"] = "BOOTS",
        ["WONDERTRAP"] = "BOOTS",
        ["WINDSCREAM"] = "BOOTS",
        ["THE KNIGHT-ERRANT"] = "BOOTS",
        ["DARKRAY VECTORS"] = "BOOTS",
        ["OBERN'S BASTION"] = "BOOTS",
        ["SHANKGONNE"] = "BOOTS",
        ["WAKE OF DESTRUCTION"] = "BOOTS",
        ["DECREE OF FLIGHT"] = "BOOTS",
        ["GHOSTMARCH"] = "BOOTS",
        ["POWERTREAD"] = "BOOTS",
        ["BEETLEBITE"] = "BOOTS",
        ["AB AETERNO"] = "BOOTS",

        // === Rings ===
        ["BLACKHEART"] = "RING",
        ["DOEDRE'S DAMNING"] = "RING",
        ["GLOWSWARM"] = "RING",
        ["GRIP OF KULEMAK"] = "RING",
        ["KALANDRA'S TOUCH"] = "RING",
        ["SEED OF CATACLYSM"] = "RING",
        ["BLISTERING BOND"] = "RING",
        ["CRACKLECREEP"] = "RING",
        ["DREAM FRAGMENTS"] = "RING",
        ["POLCIRKELN"] = "RING",
        ["LEVINSTONE"] = "RING",
        ["THE BURROWER"] = "RING",
        ["BLACKFLAME"] = "RING",
        ["MING'S HEART"] = "RING",
        ["ORIGINAL SIN"] = "RING",
        ["VEILPIERCER"] = "RING",
        ["DEATH RUSH"] = "RING",
        ["THIEF'S TORMENT"] = "RING",
        ["VIGILANT VIEW"] = "RING",
        ["CALL OF THE BROTHERHOOD"] = "RING",
        ["EVERGRASPING RING"] = "RING",
        ["HEARTBOUND LOOP"] = "RING",
        ["SNAKEPIT"] = "RING",
        ["WHISPER OF THE BROTHERHOOD"] = "RING",
        ["GIFTS FROM ABOVE"] = "RING",
        ["ICEFANG ORBIT"] = "RING",
        ["VENOPUNCTURE"] = "RING",
        ["ANDVARIUS"] = "RING",
        ["ESHTERA'S PATH"] = "RING",
        ["PERANDUS SEAL"] = "RING",
        ["SAFRIN'S RESOLVE"] = "RING",
        ["ZAIDA'S LONGEVITY"] = "RING",
        ["BEREK'S GRIP"] = "RING",
        ["BEREK'S PASS"] = "RING",
        ["BEREK'S RESPITE"] = "RING",
        ["THE TAMING"] = "RING",
        ["PRIZED PAIN"] = "RING",
        ["BURSTING DECAY"] = "RING",
        ["VENTOR'S GAMBLE"] = "RING",

        // === Amulets ===
        ["THE EVERLASTING GAZE"] = "AMULET",
        ["CARNAGE HEART"] = "AMULET",
        ["REVERED RESIN"] = "AMULET",
        ["STONE OF LAZHWAR"] = "AMULET",
        ["SUREFOOTED SIGIL"] = "AMULET",
        ["RONDEL OF FRAGILITY"] = "AMULET",
        ["THE ANVIL"] = "AMULET",
        ["YOKE OF SUFFERING"] = "AMULET",
        ["ASTRAMENTIS"] = "AMULET",
        ["FIXATION OF YIX"] = "AMULET",
        ["IDOL OF ULDURN"] = "AMULET",
        ["UNGIL'S HARMONY"] = "AMULET",
        ["BEACON OF AZIS"] = "AMULET",
        ["IMMACULATE ADHERENCE"] = "AMULET",
        ["EYE OF CHAYULA"] = "AMULET",
        ["LIGURIUM TALISMAN"] = "AMULET",
        ["SERPENT'S EGG"] = "AMULET",
        ["HINEKORA'S SIGHT"] = "AMULET",
        ["EVENTIDE PETALS"] = "AMULET",
        ["FIREFLOWER"] = "AMULET",
        ["STRUGGLESCREAM"] = "AMULET",
        ["THE PANDEMONIUS"] = "AMULET",
        ["XOPH'S BLOOD"] = "AMULET",
        ["DEFIANCE OF DESTINY"] = "AMULET",
        ["IGNIFERIS"] = "AMULET",
        ["CHOIR OF THE STORM"] = "AMULET",

        // === Belts ===
        ["KEELHAUL"] = "BELT",
        ["MEGINORD'S GIRDLE"] = "BELT",
        ["MIDNIGHT BRAID"] = "BELT",
        ["BIRTHRIGHT BUCKLE"] = "BELT",
        ["BYRNABAS"] = "BELT",
        ["SOUL TETHER"] = "BELT",
        ["UMBILICUS IMMORTALIS"] = "BELT",
        ["GOREGIRDLE"] = "BELT",
        ["RYSLATHA'S COIL"] = "BELT",
        ["COWARD'S LEGACY"] = "BELT",
        ["BIJOUBORNE"] = "BELT",
        ["HEADHUNTER"] = "BELT",
        ["WAISTGATE"] = "BELT",
        ["CAT O' NINE TAILS"] = "BELT",
        ["INGENUITY"] = "BELT",
        ["MAGEBLOOD"] = "BELT",
        ["ZERPHI'S GENESIS"] = "BELT",
        ["THE GNASHING SASH"] = "BELT",
        ["DARKNESS ENTHRONED"] = "BELT",
        ["SHAVRONNE'S SATCHEL"] = "BELT",
    }.ToFrozenDictionary(StringComparer.OrdinalIgnoreCase);

    public static string? TryGetCategory(string normalizedItemName)
    {
        if (string.IsNullOrWhiteSpace(normalizedItemName))
            return null;

        foreach (var kvp in Map)
        {
            if (normalizedItemName.StartsWith(kvp.Key, StringComparison.OrdinalIgnoreCase))
                return kvp.Value;
        }

        return null;
    }
}
